# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: '3'

services:
  UserAuthentication-Service:  #Any logical name
    image: userauthentication #Ensure this is  in small lettere
    build: UserAuthentication-Service/ #Proper name of the service folder
    restart: always
    depends_on:
      - mysqlDatabase #Depends on only one DB. Don't try to give many dbs
    network_mode: host
    ports:
      - 8089:8089  #Same port given in application.yml

  UserService:
    image: userservice
    build: UserService/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongoDatabase
    network_mode: host

  ReminderService:
    image: reminderservice
    build: ReminderService/
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongoDatabase
    network_mode: host

  NoteService:
    image: noteservice
    build: NoteService/
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mongoDatabase
    network_mode: host

  CategoryService:
    image: categoryservice
    build: CategoryService/
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - mongoDatabase
    network_mode: host


  mysqlDatabase:
    image: mysql:5.5
    ports:
      - 3306:3306
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: approot
      MYSQL_PASSWORD: apppass
      MYSQL_DATABASE: keepnote

  mongoDatabase:
    image: mongo:3.2-jessie
    ports:
      - 27017:27017
    network_mode: host



