#spring:
#  data:
#    mongodb:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
#  application:
#    name: reminder-service
#
#server:
#  port: 8081
#




spring:
  data:
    mongodb:
 #     authentication-database:
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
  application:
    name: reminder-service

server:
  port: 8081

