#spring:
#  data:
#    mongodb:
# #     authentication-database:
#      username: root
#      password: root
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
#  application:
#    name: category-service
#server:
#  port: 8083



spring:
  data:
    mongodb:
 #     authentication-database:
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
  application:
    name: category-service

server:
  port: 8083