#spring:
#  data:
#    mongodb:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
#  application:
#    name: note-service
#server:
#  port: 8082

spring:
  data:
    mongodb:
      #     authentication-database:
      database: noteserviceDb
      port: 27017
      host: localhost
  application:
    name: note-service

server:
  port: 8082